### ISSUE TITLE
Make `connection.CreateReader()` accept options.

### ISSUE THREAD

**Issue by StarlkYT** [davidfowl/BedrockFramework#164]
It becomes quite redundant to always pass a IMessageReader to the ProtocolReader every time I want to read something.
So I think it might be better to just provide that IMessageReader when creating the ProtocolReader once, so I can always read without passing the IMessageReader. 

```cs
var reader = connection.CreateReader(new MyMessageReader());
await reader.ReadAsync();
```

Thoughts?

**Comment by thenameless314159** [comment]
Hello, I don't think this goes into the scope of the class since it was made non-generic in order to be usable with different kind of ProtocolReader at once. 

The change mentionned in ur issue would require to introduce a new public strongly-typed generic type that may not be necessary since an extension method could be sufficient (user defined or made generic with a static generic protocol store within the bedrock framework):

``` csharp
namespace MyProtocolNamespace;

public static class MyProtocolExtensions
{
    // suppose we implemented a singleton pattern in our IMessageReader<T>
    public static ValueTask<ProtocolReadResult<MyResult>> ReadAsync(this ProtocolReader reader, CancellationToken token) 
        => reader.ReadAsync(MyMessageReader.Instance, token);
}
```

**Comment by StarlkYT** [comment]
Hi, you're completely right, I missed this point. The idea of creating an extension class sounds much better. Thanks!
