### ISSUE TITLE
Question about using some code piece in `Server.cs` 

### ISSUE THREAD

**Issue by TheVeryStarlk** [davidfowl/BedrockFramework#169]
for each connection a running listener instance gets it calls an execute connection [method](https://github.com/davidfowl/BedrockFramework/blob/main/src/Bedrock.Framework/Server/Server.cs#L203) and does not await it, and that [method's](https://github.com/davidfowl/BedrockFramework/blob/main/src/Bedrock.Framework/Server/Server.cs#L153) first line is an awaited task yield method. So my question is, what is the reason behind doing this instead of just calling `Task.Run` and passing the connection delegate's method.

**Comment by davidfowl** [comment]
Avoids closure allocations. Using Task.Yield when there's no sync context will [re-queue the existing async state machine to the thread pool](https://github.com/dotnet/runtime/blob/37445d4964a50eeff87ca7ed8cbdf251b547b779/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/YieldAwaitable.cs#L139).

There's 0 allocations when you do it this way. When you use `Task.Run` there's a new Task allocation, a delegate allocation and a closure allocation (because there's state that would be captured here).

**Comment by TheVeryStarlk** [comment]
Makes sense. Thank you for this response. I asked this because I had similar code where I used `Task.Run`, I will refactor it to how it is done in Bedrock.
