### ISSUE TITLE
Add performance tests

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/BedrockFramework#23]
Add BenchmarkDotNet microbenchmarks for ProtocolReader

**Comment by alistairjevans** [comment]
I'm taking a look at adding the ProtocolReader benchmarks. 

I've got a simple benchmark right now which reads x chunks from a pipe, each chunk of fixed size; a super-simple IMessageReader just moves the consumed and examined positions along each time it is called.

I'm thinking of having a benchmark for:
 - Reading messages where all the data is immediately available (i.e. Writer.Complete has already been called)
 - Reading messages where the data is gradually available, specifically available in batches that cross chunk size boundaries.

I have a question about resetting pipes...I'm trying to keep the amount of setup work done inside the benchmark method to an absolute minimum, so ideally I'd do all data and pipe write operations in the ``GlobalSetup`` section.  The ``IterationSetup`` isn't great for microbenchmarks, otherwise I'd use that.

I'm currently forced to use an approach similar to:

```csharp
[Benchmark]
public async ValueTask ReadChunkedProtocol()
{
    // Get some memory to 'fake' write to - I don't like doing this here
    var writeMemory = dataPipe.Writer.GetMemory(ChunkSize * ChunkCount);
    // Tell the pipe we've put something in the memory block (we haven't).
    dataPipe.Writer.Advance(ChunkSize * ChunkCount);
    dataPipe.Writer.Complete();

    // do actual benchmark work...

    dataPipe.Reader.Complete();

    // Reset the pipe back to 0.
    dataPipe.Reset();
}
```

My instinct is that the ``GetMemory`` call will really throw off the timings. Do you know if there's a way to pre-allocate the 'Memory' object in the ``GlobalSetup``, and make the pipe re-use it *after* the ``Reset`` call, rather than having to get that memory block from scratch in each iteration? My lack of Pipelines experience may just be letting me down here.

**Comment by davidfowl** [comment]
This might be a good place to start from https://github.com/aspnet/AspNetCore/blob/df33890548214e6f296c54729f2d5a8bc253f1a1/src/Servers/Kestrel/perf/Kestrel.Performance/HttpParserBenchmark.cs

https://github.com/aspnet/AspNetCore/blob/df33890548214e6f296c54729f2d5a8bc253f1a1/src/Servers/Kestrel/perf/Kestrel.Performance/RequestParsingBenchmark.cs

https://github.com/aspnet/AspNetCore/blob/df33890548214e6f296c54729f2d5a8bc253f1a1/src/Servers/Kestrel/perf/Kestrel.Performance/PipeThroughputBenchmark.cs

**Comment by alistairjevans** [comment]
Thanks for the reference points. I've used some of the style of them for inspiration.
Just about to raise a PR for this.
