### ISSUE TITLE
IProtocol abstraction / Application facing interface

### ISSUE THREAD

**Issue by JanEggers** [davidfowl/BedrockFramework#4]
is there a common pattern to express HttpApplication, MqttApplication and others?

for me it is about transforming  IDuplexPipe to IProtocol. What I think of is:

```
public interface IProtocol<TRequest,TResponse>
  {
    ChannelReader<TRequest> Input { get; }
    ChannelWriter<TResponse> Output { get; }
  }

public interface IProtocol<TMsg> : IProtocol<TMsg,TMsg>
  {
  }
```

**Comment by JanEggers** [comment]
or maybe

**Comment by davidfowl** [comment]
@JanEggers you're onto something there and I've had ideas about this for a while. Do you want to help spike this idea?

```C#
public interface IProtocol<TRequest, TResponse>
{
    ChannelReader<TRequest> Input { get; }
    ChannelWriter<TResponse> Output { get; }
}
```

We should spike some implementations to see how that interface holds up against some real protocols.

**Comment by JanEggers** [comment]
> Do you want to help spike this idea?

sure

**Comment by davidfowl** [comment]
Some things to think about:
- If we use Channels, are they bounded (they need to be). 
- With this model, you have to allocate request object before reading and a response type object before writing (they would be hard to pool as well because it's hard to know when you're done with it).
- Do you lose the connection object or is it still around? (If not, how do you abort or get access to other features etc).

**Comment by JanEggers** [comment]
> With this model, you have to allocate request object before reading and a response type object before writing (they would be hard to pool as well because it's hard to know when you're done with it).

More general how should request and response be implemented? right now in mqttnet they are regular classes with strings and and possilbly nested object Properties. so there are also allocations inside the msg not just the msg itself. And there is some cpu wasted for string encoding even if it is not sure if the user code needs to have that data as a string.

If you aim for zero allocations the messages need to be ref structs that just slices up the spans.
And with that approach we cannot use channels because ref structs dont like async.

Another issue at least for mqtt are var int encoded parts of the header and in v5 also in the body, so during write I have to write the body before knowing the length, so I cannot directly write the response in the pipe but have to use intermidiate buffers.

> Do you lose the connection object or is it still around? (If not, how do you abort or get access to other features etc).

I think the connection object is very usefull so it should stick around. I was thinking that just adding a Protocol Property that exposes the interface should be fine.

**Comment by davidfowl** [comment]
> More general how should request and response be implemented? right now in mqttnet they are regular classes with strings and and possilbly nested object Properties. so there are also allocations inside the msg not just the msg itself. And there is some cpu wasted for string encoding even if it is not sure if the user code needs to have that data as a string.

That's a choice of a specific Request/Response type.

> If you aim for zero allocations the messages need to be ref structs that just slices up the spans.
And with that approach we cannot use channels because ref structs dont like async.

Not zero allocations , but zero allocations amortized. So the ability to pool and reuse objects is important even if the default implementation doesn't do that. It might be possible by adding a dispose to the Request/Response object.

> Another issue at least for mqtt are var int encoded parts of the header and in v5 also in the body, so during write I have to write the body before knowing the length, so I cannot directly write the response in the pipe but have to use intermidiate buffers.

This is a solution to that https://github.com/AArnott/Nerdbank.Streams/blob/9d1df2ab1d3699988a23183913dfdaf19eaf3891/doc/PrefixingBufferWriter.md.

> I think the connection object is very usefull so it should stick around. I was thinking that just adding a Protocol Property that exposes the interface should be fine.

👍

**Comment by JanEggers** [comment]
> This is a solution to that https://github.com/AArnott/Nerdbank.Streams/blob/9d1df2ab1d3699988a23183913dfdaf19eaf3891/doc/PrefixingBufferWriter.md.

that is a fixed int prefix mqtt has var int 
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Table_2.4_Size

**Comment by JanEggers** [comment]
@davidfowl hi I pulled in your bits into mqttnet, and the Protocol & tcp client work like a charm:

https://github.com/JanEggers/MQTTnet/tree/aspnetcore3/Source/MQTTnet.AspnetCore

I had some issues in the process:

1. I used the mqtt connection handler from the server in the client that deadlocked connect.
also using the handler returned the builder as IConnectionBuilder so Build returned a connectiondelegate => maybe rename Client.Build() to Client.BuildClient() or factor that different.

**Comment by davidfowl** [comment]
Great! That looks awesome!

**Comment by davidfowl** [comment]
Hey @JanEggers I pushed this to a nuget feed so you can avoid using the project reference for now https://github.com/davidfowl/BedrockFramework#using-ci-builds.

**Comment by JanEggers** [comment]
thx for letting me know. and have nice holidays

**Comment by MithrilMan** [comment]
nice move on moving it to nuget, I'm using it in a project I just started a couple of weeks ago
https://github.com/MithrilMan/MithrilShards 
specifical implementation at https://github.com/MithrilMan/MithrilShards/tree/master/src/MithrilShards.Network.Bedrock

As a note, I think would be nice to have an explicit method to override from ConnectionHandler to catch peer disconnection, so other than 
`public abstract Task OnConnectedAsync(ConnectionContext connection);`
we should have a `public abstract Task OnDisconnectedAsync(ConnectionContext connection, Exception ex);`

not sure if the exception should be there or in ConnectionContext, but the logic is that at application level I should be able to catch connection exception caused by the other part that dropped the connection in order to handle such case (I could catch it probably in OnConnectAsync but to me it doesn't sounds the right place

P.S.
good job on this library, is it planned to be merged into next dotnet core release somehow?

**Comment by davidfowl** [comment]
> nice move on moving it to nuget, I'm using it in a project I just started a couple of weeks ago
https://github.com/MithrilMan/MithrilShards
specifical implementation at https://github.com/MithrilMan/MithrilShards/tree/master/src/MithrilShards.Network.Bedrock

Nice!! I need to iterate on the interface a bit since it forces allocations today. There needs to be a protocol reader interface that either returns a disposable or has an Advance method on it. I hope to get feedback for this.

> As a note, I think would be nice to have an explicit method to override from ConnectionHandler to catch peer disconnection, so other than
public abstract Task OnConnectedAsync(ConnectionContext connection);
we should have a public abstract Task OnDisconnectedAsync(ConnectionContext connection, Exception ex);

This could be built on top. Right now the lowest level is basically a single call and when that task completes.

> good job on this library, is it planned to be merged into next dotnet core release somehow?

Thanks! This is my playground to figure out what is useful to people. I'm not sure if all of it will make it into .NET Core but hopefully some of the core abstractions will at some point.
